---
- name: keycloak | prereq 
  hosts: all
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - common
  tags:
    - common


- name: keycloak | docker-ce
  hosts: all
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - docker-ce
  tags:
    - docker-ce


- name: keycloak | keycloak
  hosts: all
  remote_user: ansible
  environment: "{{ proxy_env }}"
  roles:
    - keycloak
  tags:
    - keycloak

