- name: docker | docker-compose install
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod 755 /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose
    warn: false

