---
- name: docker | prereq
  include: prereq.yml
  when: deploy_docker|bool

    
- name: docker | lvm partition
  include: lvm.yml
  when: 
    - deploy_docker_lvm_storage|bool
    - deploy_docker|bool

- name: docker | docker-compose
  include: docker-compose.yml

- name: docker | setup
  include: docker.yml
