version: "3.2"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: keycloak
        volumes:
            - ${PWD}/data/pgdata:/var/lib/postgresql/data
        restart: always
    keycloak:
        image: jboss/keycloak:8.0.0
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=postgres
            - DB_USER=admin
            - DB_PASSWORD=password
            - DB_PORT=5432
            - DB_ADDR=postgres
            - DB_DATABASE=keycloak
            - PROXY_ADDRESS_FORWARDING=true
        restart: always
    nginx:
        image: nginx:alpine
        depends_on:
            - keycloak
        volumes:
            - ${PWD}/config/default.conf:/etc/nginx/conf.d/default.conf
            - ${PWD}/config/ssl-certs:/etc/nginx/ssl-certs
        ports:
            - '443:443'
            - '80:80'
        restart: always
